-- Auckland 试点种子数据 (8 点, 坐标为近似值; ETL 接入后以 (source_name, source_id) 幂等覆盖)
insert into public.places
(name, description, category, geom, region, city, distance_km, estimated_time_minutes,
 difficulty, dog_allowed, parking, accessibility, camping_allowed, fishing_allowed,
 swimming_allowed, family_friendly, fee_required, source_name, source_url, source_id, last_updated, raw)
values
('Karekare Falls', 'Short walk to a scenic waterfall in the Waitākere Ranges.', 'waterfall'::place_category,
  ST_SetSRID(ST_MakePoint(174.4727, -37.0015),4326)::geography,
  'Auckland', 'Auckland', null, 30,
  'easy', null, null, null,
  null, null, null,
  null, null,
  'Seed (verify via DOC ETL)', null, 'seed-karekare-falls', now(), null),
('Hunua Falls', '30m waterfall in Hunua Ranges Regional Park with picnic area.', 'waterfall'::place_category,
  ST_SetSRID(ST_MakePoint(175.0624, -37.0672),4326)::geography,
  'Auckland', 'Auckland', null, 20,
  'easy', null, null, null,
  null, null, null,
  null, null,
  'Seed (verify via DOC ETL)', null, 'seed-hunua-falls', now(), null),
('Mount Eden (Maungawhau)', 'Auckland's highest volcanic cone, 360° city views.', 'lookout'::place_category,
  ST_SetSRID(ST_MakePoint(174.764, -36.88),4326)::geography,
  'Auckland', 'Auckland', null, null,
  'easy', null, true, null,
  null, null, null,
  null, null,
  'Seed (verify via council ETL)', null, 'seed-mt-eden', now(), null),
('Cornwall Park', 'Large pastoral park around One Tree Hill, walks and picnic areas.', 'park'::place_category,
  ST_SetSRID(ST_MakePoint(174.7816, -36.9025),4326)::geography,
  'Auckland', 'Auckland', null, null,
  'easy', true, true, null,
  null, null, null,
  null, null,
  'Seed (verify via council ETL)', null, 'seed-cornwall-park', now(), null),
('Piha Beach', 'Iconic west coast black-sand surf beach. Swimming only between flags.', 'beach'::place_category,
  ST_SetSRID(ST_MakePoint(174.4667, -36.9548),4326)::geography,
  'Auckland', 'Auckland', null, null,
  null, null, null, null,
  null, null, true,
  null, null,
  'Seed (verify via council ETL)', null, 'seed-piha', now(), null),
('Muriwai Beach (Gannet Colony)', 'Clifftop gannet colony viewing, black-sand beach and walks.', 'lookout'::place_category,
  ST_SetSRID(ST_MakePoint(174.43, -36.8347),4326)::geography,
  'Auckland', 'Auckland', null, null,
  null, null, true, null,
  null, null, null,
  null, null,
  'Seed (verify via DOC ETL)', null, 'seed-muriwai', now(), null),
('Takapuna Beach', 'North Shore family beach with promenade, swimming friendly.', 'beach'::place_category,
  ST_SetSRID(ST_MakePoint(174.7734, -36.785),4326)::geography,
  'Auckland', 'Auckland', null, null,
  null, null, true, null,
  null, null, true,
  null, null,
  'Seed (verify via council ETL)', null, 'seed-takapuna', now(), null),
('Arataki Visitor Centre', 'Gateway to Waitākere Ranges, panoramic lookout, track info.', 'lookout'::place_category,
  ST_SetSRID(ST_MakePoint(174.546, -36.952),4326)::geography,
  'Auckland', 'Auckland', null, null,
  'easy', null, true, null,
  null, null, null,
  null, null,
  'Seed (verify via DOC ETL)', null, 'seed-arataki', now(), null)
on conflict (source_name, source_id) do nothing;
